version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "quizzer_api"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4000:4000
