AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-prisma

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  DbUrl:
    Type: String
  PrismaTarget:
    Type: String
  QuizzerApiCertificateArn:
    Type: String
  QuizzerApiDomainName:
    Type: String
  HostZoneId:
    Type: String
  ExternalDependencies:
    Type: String
    Default: "infra frontend-next cdk.out"

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods
      # AllowHeaders: "*"
      # AllowMethods: "DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT"
      # AllowOrigin: "*"
      Domain:
        CertificateArn: !Ref QuizzerApiCertificateArn
        DomainName: !Ref QuizzerApiDomainName
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostZoneId
      EndpointConfiguration:
        Type: EDGE
  SamQuizzerApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          DATABASE_URL: !Ref DbUrl
          PRISMA_CLI_BINARY_TARGETS: !Ref PrismaTarget
          # PRISMA_QUERY_ENGINE_LIBRARY: ../node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node
      Events:
        QuizzerApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayRestApi
            Auth:
              ApiKeyRequired: true
    Metadata: # Manage esbuild properties
      DockerTag: nodejs20.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Enabled: true
      Name: !Sub 'api-key'
      StageKeys: 
        - RestApiId: !Ref ApiGatewayRestApi
          StageName: Prod
    DependsOn: 
      - ApiGatewayRestApi
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiKey
      - ApiGatewayRestApi
    Properties:
      ApiStages:
          - ApiId: !Ref ApiGatewayRestApi
            Stage: Prod
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      UsagePlanName: !Sub 'api-plan'
  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - ApiUsagePlan
      - SamQuizzerApiFunction
      - ApiGatewayRestApi
    Properties : 
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

Outputs:
  # SamQuizzerApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SamQuizzerApiFunction:
    Description: "SAM Quizzer Api Lambda Function ARN"
    Value: !GetAtt SamQuizzerApiFunction.Arn
  SamQuizzerApiFunctionIamRole:
    Description: "Implicit IAM Role created for SAM Quizzer Api function"
    Value: !GetAtt SamQuizzerApiFunctionRole.Arn
