AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-prisma

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    BinaryMediaTypes:
      - multipart/form-data

Parameters:
  DbUrl:
    Type: String
  Region:
    Type: String
  PrismaTarget:
    Type: String
  QuizzerApiCertificateArn:
    Type: String
  QuizzerApiDomainName:
    Type: String
  HostZoneId:
    Type: String
  CognitoUserpoolId:
    Type: String
  CognitoAppClientId:
    Type: String
  QuizImageS3BucketName:
    Type: String
  ExternalDependencies:
    Type: String
  Akey:
    Type: String
  SAkey:
    Type: String
    Default: 'infra frontend-next cdk.out'
  TodoCheckStatusTableArn:
    Type: String
    Description: 'DynamoDB Table ARN for Todo check status'

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      OpenApiVersion: 3.0.1
      # ApiKeySourceType: HEADER
      # Auth:
      #   # ApiKeyRequired: true # sets for all methods
      #   # AddApiKeyRequiredToCorsPreflight: false
      #   UsagePlan:
      #     CreateUsagePlan: PER_API
      #     UsagePlanName: no-required-api-key-in-options-method-usage-plan
      #     Throttle:
      #       BurstLimit: 100
      #       RateLimit: 50
      Domain:
        CertificateArn: !Ref QuizzerApiCertificateArn
        DomainName: !Ref QuizzerApiDomainName
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostZoneId
      EndpointConfiguration:
        Type: EDGE
      Cors:
        AllowMethods: "'DELETE,POST,GET,OPTIONS,PUT,PATCH'"
        AllowHeaders: "'Origin,X-Requested-With,Content-Type,Accept,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: false
        MaxAge: "'3600'"
  SamQuizzerApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          REGION: !Ref Region
          DATABASE_URL: !Ref DbUrl
          PRISMA_CLI_BINARY_TARGETS: !Ref PrismaTarget
          AWS_COGNITO_USERPOOL_ID: !Ref CognitoUserpoolId
          AWS_COGNITO_APPCLIENT_ID: !Ref CognitoAppClientId
          QUIZ_IMAGE_S3_BUCKET: !Ref QuizImageS3BucketName
          AKEY: !Ref Akey
          SAKEY: !Ref SAkey
          TODO_CHECK_STATUS_TABLE_ARN: !Ref TodoCheckStatusTableArn
          # PRISMA_QUERY_ENGINE_LIBRARY: ../node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
              Resource: !Ref TodoCheckStatusTableArn
      Events:
        QuizzerApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayRestApi
            # Auth:
            #   ApiKeyRequired: true
    Metadata: # Manage esbuild properties
      DockerTag: nodejs20.x-v1
      DockerContext: ../
      Dockerfile: Dockerfile

Outputs:
  # SamQuizzerApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SamQuizzerApiFunction:
    Description: 'SAM Quizzer Api Lambda Function ARN'
    Value: !GetAtt SamQuizzerApiFunction.Arn
  SamQuizzerApiFunctionIamRole:
    Description: 'Implicit IAM Role created for SAM Quizzer Api function'
    Value: !GetAtt SamQuizzerApiFunctionRole.Arn
