name: Deploy Backend to AWS (dev)

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup dependencies(backend)
      id: setup-dependencies-backend 
      run: cd ./backend-nest && npm ci

    - name: Setup dependencies(infra)
      id: setup-dependencies-infrra 
      run: cd ./infra && npm ci
      
    - name: nest build
      id: build-api
      run: cd ./backend-nest && npm run build

    - name: Deploy backend stack
      id: cdk-deploy-backend
      run: cd ./infra && npx cdk deploy BackendStack --require-approval never
